language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
  - '7'
  - '6'

before_script:
  - npm prune
# Enable this when we are ready to publish 1.x
# after_success:
#   - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
